language: ruby
rvm:
- '2.2'
cache: bundler
install:
- bundle install
script:
- bundle exec middleman build
- bundle exec middleman sync
- bash <(curl -s https://peek.run/ci)
env:
  global:
    - GA_TRACKING_ID="UA-36013038-3"
    - PARSE_APPLICATION_ID=vCnXJREUqglwhFxH88GKjG4pAFDh043OWN7qAsoj
    - secure: "wqTcTeES6me8WbOooDtVCi8uCnjj28cu2YynirkbR301BK/dmrITBmaUxkRdnoGjFS+zgvN3t+SO8+91O+LwjmmmlHAQxv0Aco6EY1MbpWN/bbu6EUQe77sPHMHktTL9XSykjyf1Z6GPpzZTicgxTZtQqqA6nVTV6BXhJUWxrQdBiztX4wCxiMGWpQ7tc1jqNcdsbnEOeeEaoZ9X6lLvQJ2vPlvdK13mo5X6vjFZfeIUwVz4DSd3M23dUsl87tesmYzHXe+jZ+H+1QrrpmIt4MlmVI+y9mz/+KAEtG8NH5Gr9pNoDbaj6rrjE0CfRCwSxSNK1AlVwfrwA9mzMQge9UaITzdsmAdsRCDmRIOTMSSP19+qDOR/VbVTM9FB9uawQnhL6d3Y6MBhtF+gWMu2qtvbAuu1AFnaMjCFRRcRtRdoelTNM+xwpc6VZyPI+eBA6bCoHvB6bwh6Uzd4VPzhBTNvmCGdVWxmW0yEH/jmGO6eTFtUadZONh0DSQ/iFybbTS2QzuRF4+8emUUH87VJGQ7CWqbqFQtkVS8uPCBF1Vd0sBSY2qXrhdqZt1SMWkK3IB2TfQKUVYYy8OMOFEw3SX+aPXdU956dAG0SKpSSUkc6l7LeMgaiz9flHA3FDkMj0IjBiQF6D+zgx29Q4ubb8KUyed29rWRysRbsStaGgmE="
    - AWS_REGION='us-west-2'
    - AWS_BUCKET='www.happilyeverattfield.com'
    - AWS_ACCESS_KEY_ID=AKIAIULHPJHQWLJXCGMA
    - secure: "GG+AP7mfePJV3vnBYd+0sTWlCcGfXzqdTQnLAeRvTNfARKhCqlDcapRYCjnl9gSU/FkxxdKYV7JrlrFQfauuW7x3Fq1ozOUjGXu6AXvOjZJOepBFkGrYP0h/WZoLqDX+4G/+Z2V2M+ftvKgGxlkT5OoezdkFuZQacOFzBZRN59PU2EEKVz9V62wSXeVqZYuq2PxrgP59la140bLNJ8uIxogXYX0MdBMHpTKLr2qIrDRKM1BUHUWv2b5iGi7v4NswOBoJT2V5+KzecdJTknn51ngYTGKT3uDG0OKuTZKVZChfSI9m/U6InRCeiktm2mtGUTUu9j8hUE8U2i7qo3qZEWO3HlVgPEJpVTy3g89UgogmD70GKI33PLUvAyiqSE6JaHFLNEICOInCmPRkd+2TripX80YHajn3B2FKfn6UL0TsJSdVhsfOf24s1JteraVBYPjipGCExsDV9KPdAT5S0cDzF8GuPCJClFgkimbF3OMhV4tmrL8tSx4dUQJUc14pMtwuebkmw6fyx+8w4glER0CcoO9Gih321xsjQYTWhgE2uKhl+dGaXnCoBNoFpUV5l72ef5Jg6HfExSgX6Do2GgMB54bVmi9/yVW/OlJwA/2pSif4Rr3qIRRQvferlS9HMkq5FoGO2EtrOqotZvQCHOq47DkUXB+rUQO5rXqtALE="
